### PR TITLE
Added a simple Permakill plugin

### PR DESCRIPTION
**Pull request by Thadah**
I ported my old Permakill plugin from NS 1.0 and adjusted it to match the NS 1.1 standards, as well as some optimizations to the old code.

The plugin has been tested with different ways of death and seems to work perfectly.

### CODE REVIEW

**Comment by stnngfm** [comment]
Great Plugin!

**Comment by Rubberbandits** [comment]
we really need a 1.1 plugin repository

**Comment by Thadah** [comment]
I agree with that

**Comment by Chessnut** [comment]
I would merge this, but I'd suggest you use `character:ban()` instead of just constantly killing the player when spawning. Also, can you add pk in front of the config names? Just doing so to be safe against naming conflict.

**Comment by Thadah** [comment]
Alright, I will change it to match what you asked (actually it makes more sense, but I thought there wasn't a `character:ban()` implemented into the code).

**Comment by Thadah** [comment]
Doing `character:ban()` makes the client spawn and be immortal after spawnTime, with movement and actions restricted because he is in the menu, but spawned. I think this is the part of code that creates the issue in CHAR:kick():

```
        if (isCurrentChar) then
            client:setNetVar("char", nil)
            client:Spawn()
        end
    end
end
```

**Comment by Chessnut** [comment]
They become locked upon spawning without a character.

**Comment by Thadah** [comment]
I tried to `client:KillSilent()` with them, but it doesn't seem to work

So should I let them spawn?

**Comment by Chessnut** [comment]
Why do you need to be constantly killing the player though? They are
spawned, but restricted and invisible as if they are not even there. Plus
the character menu is open so just either create or load a character.

**Comment by Thadah** [comment]
No I didn't mean that. I meant I tried to do `timer.Create("pk", 0.001, 1, function() client:KillSilent() end)` as a workaround for the client to be spawning locked after his character being banned.

And no, they are not invisible, they spawn visible and locked.

**Comment by Thadah** [comment]
Here's a video that explains better what I'm trying to say:
https://www.youtube.com/watch?v=wgwPW6bvXEI

**Comment by Chessnut** [comment]
Fixed in 118834e1b58fdc94163bf2b022cc9eaea72c353f

Also, why don't you just ban the character upon death? Unless you want them to wait while dead.

**Comment by Thadah** [comment]
Well I think myself permakill differs from simple character banning, because it's a permanent death for the characters, so I prefered that the  "You're Dead" screen appeared during `spawnTime` before the ban.

If you want me to do it upon death it's fine by me.

**Comment by Thadah** [comment]
So...should I change it?

**Pull request merged**
