### PR TITLE
Merge sh_commands.lua

### PR DESCRIPTION
**Pull request by DeadiKation**
Kinda new to the whole suggesting additions onto Github, but I simply added /flagtake so that you can take flags from a character.

### CODE REVIEW

**Comment by Rubberbandits** [comment]
Nice commit deadi, reminds me that I have to merge my clothing and gender
commits ^^

**Comment by Chessnut** [comment]
Why is the whole file changed?

**Comment by DeadiKation** [comment]
To be honest, I don't know, as I said I'm kinda new to the whole adding suggestions or merging files on Github. If you want just edit in the flag take command or not.

**Comment by Chessnut** [comment]
Added a version where you a menu opens to take flags.

**Comment by Rubberbandits** [comment]
My cooling system has stopped pumping.


http://www.amazon.com/Corsair-Series-Performance-Cooler-CWCH70/dp/B003XOR00I
That's the new one I got recommended.

**Comment by Rubberbandits** [comment]
Lmao chessnut i didn't me to send  to you lol

**Pull request closed without merging**
